# Generated by Django 3.1.4 on 2020-12-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Available_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('copies', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('book_type', models.CharField(choices=[('OTHER', 'Other'), ('BIOGRAPHY', 'Biography'), ('FICTION', 'Fiction'), ('NON-FICTION', 'Non-Fiction')], default='OTHER', max_length=25)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libraryapi.author')),
                ('book_available', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.available_book')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(null=True)),
                ('contact_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ucid', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('faculty', models.CharField(max_length=25)),
                ('books_requested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_req', to='libraryapi.book')),
                ('books_withdrawn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_with', to='libraryapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unavailable_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_availability', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=25)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.person')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50)),
                ('no_books', models.IntegerField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.person')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_unavailable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.unavailable_book'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libraryapi.publisher'),
        ),
        migrations.AddField(
            model_name='available_book',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.location'),
        ),
    ]
