# Generated by Django 3.1.4 on 2020-12-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('copies', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
