# Generated by Django 3.1.4 on 2020-12-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_available',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.available_book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_unavailable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.unavailable_book'),
        ),
    ]
