# Generated by Django 3.1.4 on 2020-12-08 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('aName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ucid', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisherID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pName', models.CharField(max_length=30)),
                ('pCountry', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='books_requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_req', to='libraryapi.book'),
        ),
        migrations.AddField(
            model_name='customer',
            name='books_withdrawn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_with', to='libraryapi.book'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.publisher'),
            preserve_default=False,
        ),
    ]
