# Generated by Django 3.1.4 on 2020-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('aName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisherID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pName', models.CharField(max_length=30)),
                ('pCountry', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
