# Generated by Django 3.1.4 on 2020-12-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0002_auto_20201209_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_book',
            name='boolean',
            field=models.BooleanField(default=True),
        ),
    ]
