# Generated by Django 3.1.4 on 2020-12-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0002_auto_20201212_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PROFESSOR', 'Professor')], default='STUDENT', max_length=25),
        ),
        migrations.AddField(
            model_name='professor',
            name='years_taught',
            field=models.IntegerField(null=True),
        ),
    ]
