# Generated by Django 3.1.4 on 2020-12-08 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0002_auto_20201208_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bookID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='bookID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book'),
            preserve_default=False,
        ),
    ]
