# Generated by Django 3.1.4 on 2020-12-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0003_auto_20201208_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
