# Generated by Django 3.1.4 on 2020-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0004_remove_available_book_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faculty',
            field=models.CharField(choices=[('OTHER', 'Other'), ('SCI', 'Biography'), ('ENGG', 'Fiction'), ('MATH', 'Non-Fiction'), ('ART', 'Arts'), ('IT', 'Information Technology')], default='OTHER', max_length=25),
        ),
    ]
