# Generated by Django 3.1.4 on 2020-12-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0004_auto_20201208_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='aName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pCountry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisherID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libraryapi.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libraryapi.publisher'),
        ),
    ]
