# Generated by Django 3.1.4 on 2020-12-11 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0005_auto_20201211_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('available', models.BooleanField(default=True, primary_key=True, serialize=False)),
                ('next_availability', models.CharField(max_length=25)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.location')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_available',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_unavailable',
        ),
        migrations.AlterField(
            model_name='person',
            name='books_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_req', to='libraryapi.book'),
        ),
        migrations.AlterField(
            model_name='person',
            name='books_withdrawn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_with', to='libraryapi.book'),
        ),
        migrations.AlterField(
            model_name='person',
            name='faculty',
            field=models.CharField(choices=[('OTHER', 'Other'), ('SCI', 'Sciences'), ('ENGG', 'Engineering'), ('MATH', 'Mathematics'), ('ART', 'Arts'), ('IT', 'Information Technology')], default='OTHER', max_length=25),
        ),
        migrations.DeleteModel(
            name='Available_Book',
        ),
        migrations.DeleteModel(
            name='Unavailable_Book',
        ),
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.bookstatus'),
        ),
    ]
