# Generated by Django 3.1.4 on 2020-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0005_auto_20201208_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('BIOGRAPHY', 'Biography'), ('FICTION', 'Fiction'), ('NON-FICTION', 'Non-Fiction')], default='OTHER', max_length=25),
        ),
    ]
