# Generated by Django 3.1.4 on 2020-12-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0006_auto_20201208_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Unavailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.location')),
            ],
        ),
    ]
