# Generated by Django 3.1.4 on 2020-12-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0006_auto_20201211_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstatus',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.location'),
        ),
        migrations.AlterField(
            model_name='bookstatus',
            name='next_availability',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
