# Generated by Django 3.1.4 on 2020-12-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0007_book_available_book_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
