# Generated by Django 3.1.4 on 2020-12-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0008_location_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Available',
            new_name='Available_Book',
        ),
        migrations.RenameModel(
            old_name='Book_Unavailable',
            new_name='Unavailable_Book',
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('no_books', models.IntegerField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book')),
            ],
        ),
    ]
