# Generated by Django 3.1.4 on 2020-12-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0009_auto_20201208_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='series_name',
            field=models.CharField(max_length=50),
        ),
    ]
