# Generated by Django 3.1.4 on 2020-12-12 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('copies', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('book_type', models.CharField(choices=[('OTHER', 'Other'), ('BIOGRAPHY', 'Biography'), ('FICTION', 'Fiction'), ('NON-FICTION', 'Non-Fiction')], default='OTHER', max_length=25)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libraryapi.author')),
            ],
        ),
        migrations.CreateModel(
            name='BooksRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid', models.IntegerField(null=True)),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('book_year', models.IntegerField()),
                ('book_language', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(null=True)),
                ('contact_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('books_withdrawn', models.IntegerField(null=True)),
                ('ucid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('faculty', models.CharField(choices=[('OTHER', 'Other'), ('SCI', 'Sciences'), ('ENGG', 'Engineering'), ('MATH', 'Mathematics'), ('ART', 'Arts'), ('IT', 'Information Technology')], default='OTHER', max_length=25)),
                ('books_requested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_required', to='libraryapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=25)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.person')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50)),
                ('no_books', models.IntegerField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.person')),
            ],
        ),
        migrations.CreateModel(
            name='OrderContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book')),
                ('orderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.order')),
            ],
        ),
        migrations.CreateModel(
            name='BooksWithdrawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawerid', models.IntegerField()),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('next_availability', models.CharField(blank=True, max_length=25)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.location')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapi.bookstatus'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libraryapi.publisher'),
        ),
    ]
