# Generated by Django 3.1.4 on 2020-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0003_auto_20201212_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
